# Generated by Django 5.1.4 on 2025-01-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Mobiles Phones', 'Mobile Phones')], default='IT', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(),
        ),
    ]
